#!/bin/sh  

#chkconfig:2345 55 75 
  
. /etc/rc.d/init.d/functions  
  
appName="sphinx"  
count=`ps -ef| grep searchd|grep -v grep|wc -l`
  
stop(){  
    /usr/local/sphinx/bin/searchd -c /usr/local/sphinx/etc/sphinx.conf --stop > /dev/null 2>&1   
        ret=$?  
        if [ $ret -eq 0 ]; then  
            action $"Stoping $appName: " /bin/true  
        else  
            action $"Stoping $appName: " /bin/false  
        fi  
    return $ret  
}  
  
start(){  

     [[ $count -ne 0 ]] && stop 

     indexer

    /usr/local/sphinx/bin/searchd -c /usr/local/sphinx/etc/sphinx.conf > /dev/null 2>&1   
        ret=$?  
        if [ $ret -eq 0 ]; then  
            action $"Starting $appName: " /bin/true  
        else  
            action $"Starting $appName: " /bin/false  
        fi  
    return $ret  
}  
  
indexer(){  
	sleep 2
        /usr/local/sphinx/bin/indexer -c /usr/local/sphinx/etc/sphinx.conf --all > /dev/null 2>&1  
    ret=$?  
        if [ $ret -eq 0 ]; then  
            action $"$appName making index: " /bin/true  
        else  
            action $"$appName making index: " /bin/false  
        fi  
        return $ret  
}  
  
  
case $1 in  
    restart)  
    start  
    ;;  
  
    stop)  
    stop  
    ;;  
      
    start)  
    start  
    ;;  
esac  
  
exit 0  
